# Generated by Django 4.0.4 on 2022-05-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_ticket_id_booking_event_id'),
        ('events', '0002_rename_date_event_start_date_event_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=1000009999),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
