# Generated by Django 4.0.4 on 2022-06-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_price_delete_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.categories'),
        ),
    ]
