# Generated by Django 4.0.4 on 2022-05-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('events', '0002_rename_date_event_start_date_event_end_date'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='user.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='booking.payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_id',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='events.ticket'),
            preserve_default=False,
        ),
    ]
