# Generated by Django 4.0.4 on 2022-05-31 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_date_event_start_date_event_end_date'),
        ('booking', '0002_booking_email_booking_payment_id_booking_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='event_id',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
    ]
