# Generated by Django 4.0.4 on 2022-06-01 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_payment_masked_card_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking_id',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
            preserve_default=False,
        ),
    ]
