# Generated by Django 4.0.4 on 2022-06-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_payment_date_alter_payment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(default='placeholdername', max_length=250),
            preserve_default=False,
        ),
    ]
