# Generated by Django 4.0.4 on 2022-06-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_address_booking_street_name_booking_house_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='house_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
