# Generated by Django 4.0.4 on 2022-06-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_booking_amount_alter_booking_zip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='email',
            new_name='user_id',
        ),
    ]
