# Generated by Django 4.0.4 on 2022-06-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_rename_email_booking_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='exp_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='name_of_card_holder',
        ),
    ]
