# Generated by Django 4.0.4 on 2022-06-02 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_category_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0015_remove_payment_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
