# Generated by Django 4.0.4 on 2022-06-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_booking_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='subtotal',
            field=models.IntegerField(default=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(auto_now_add=True, default='10:10:10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.PositiveIntegerField(default=999),
            preserve_default=False,
        ),
    ]
