# Generated by Django 4.0.4 on 2022-06-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_booking_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
