# Generated by Django 4.0.4 on 2022-06-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_booking_email_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.CharField(default='lame city', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(default='prump prumpsson', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='house_num',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='street_name',
            field=models.CharField(default='some street', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='zip',
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
    ]
