# Generated by Django 4.0.4 on 2022-05-24 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.account')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.categories')),
            ],
        ),
    ]
