# Generated by Django 4.0.4 on 2022-05-31 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
