# Generated by Django 4.0.4 on 2022-06-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_category_id'),
        ('user', '0003_delete_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fav_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.categories'),
        ),
    ]
