# Generated by Django 4.0.4 on 2022-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_account_fav_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile-pics'),
        ),
    ]
