# Generated by Django 4.0.4 on 2022-06-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_account_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image_url',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
